### ISSUE TITLE
关于数据准备

### ISSUE THREAD

**Issue by ywb2018** [DataTerminatorX/Keyword-BERT#16]
请问一下，在应用的预测阶段，给定一个输入query，如何确定他是哪个domain的呢？

**Comment by ywb2018** [comment]
不同domain的关键词不一样，假如一个q他带有跨domain的关键词，那是否需要先预先判断domain？

**Comment by DataTerminatorX** [comment]
在我们的场景下，domain信息只是用来提关键词，最后都会merge成一个关键词典，使用的时候不区分domain
可以根据你们实际应用场景做adaption
