### ISSUE TITLE
在一些已公开的数据集上的测试指标怎么样？

### ISSUE THREAD

**Issue by yanbo-w** [DataTerminatorX/Keyword-BERT#4]
目前了解的公开（非通用领域）的语义匹配数据集上的指标怎么样？例如蚂蚁金服atec、lcqmc、CCKS2018微众银行等数据集上的指标如何？

**Comment by DataTerminatorX** [comment]
没测，有兴趣可以试试。
LCQMC 其实跟我们的内部数据集差不多，都是从百度知道上爬的

**Comment by yanbo-w** [comment]
在lcqmc和atec公开数据集上，用jieba提取关键词，测试的结果比原生bert基本没有提升。
这个keyword bert方法对keyword提取的质量要求很高么？还是有其他的原因？

**Comment by DataTerminatorX** [comment]
> 在lcqmc和atec公开数据集上，用jieba提取关键词，测试的结果比原生bert基本没有提升。
> 这个keyword bert方法对keyword提取的质量要求很高么？还是有其他的原因？

对的，关键词质量很重要。 jieba 的结果还是太简单(只有 tf-idf 和 text-rank)，很难得到 domain词，以及很难分出新词。 所以我们设计了一套更复杂严谨的pipeline，在我们论文里有提到，能完成 新词发现、领域词识别、词校验 等等功能
